<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    </PropertyGroup>
    
    <ItemGroup>
        <ProjectReference Include="..\Application\Application.csproj" />
        <ProjectReference Include="..\Infrastructure\Infrastructure.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="DotNetEnv" Version="3.2.0" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="10.0.12" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="MudBlazor" Version="9.9.0" />
        <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    </ItemGroup>

    <ItemGroup>
      <_ContentIncludedByDefault Remove="Components\Activities\ActivityNavigation.razor" />
      <_ContentIncludedByDefault Remove="Components\Features\Activities\ActivityDetails\ActivityTitle.razor" />
    </ItemGroup>

    <ItemGroup>
      <AdditionalFiles Include="Components\Features\ActivityDetails\Metrics\ActivityMetric.razor" />
      <AdditionalFiles Include="Components\Features\ActivityDetails\Metrics\MetricsBar.razor" />
    </ItemGroup>

</Project>
